### ISSUE TITLE
CSS - Position on self-hosted Trilium

### ISSUE THREAD

**Issue by dariuszszyc** [madodig/trilium-widget-theme-switch#3]
Hello,

In the self-hosted - should it appear in top left corner ?

![msedge_bXfk2nykYM](https://github.com/madodig/trilium-widget-theme-switch/assets/41972270/d4dc68ec-9402-47f3-8911-72f020ed25ae)

**Comment by madodig** [comment]
Hi,

no, it should appear next to the title bar buttons if you have Native Title Bars disabled, or in the top right corner if you have them enabled.
I tested this today on 0.62.4 and then I've updated to 0.62.5 and it works as expected (at least for me) on both of the versions (desktop installation on Windows 10).
<img src="https://github.com/madodig/trilium-widget-theme-switch/assets/14966219/e3c6e36e-8f46-4c74-8313-68efd3be2d57" width="200">

<img src="https://github.com/madodig/trilium-widget-theme-switch/assets/14966219/df1a662b-03e6-43c9-9afa-6c2168e27e92" width="125">

Do you have another widget that this widget might be interfering with (ie modifying the title bar buttons component)?
If you have Native Title Bar disabled, do you see the title bars component? Can you open the Dev Tools and search for "title-bar-buttons component" and/or "tab-row-widget component"? Are they there?

It should look something like this:
Native Title Bar disabled:
![image](https://github.com/madodig/trilium-widget-theme-switch/assets/14966219/ae922a2c-2fbc-4745-aed2-a4dfa6c57767)
Native Title Bar enabled:
![image](https://github.com/madodig/trilium-widget-theme-switch/assets/14966219/132cc518-6868-4b09-9fac-878ed9abd949)


Relevant lines from the widget code:
```
// Positions the widget
// If native title bar is enabled, appends container
if (isNativeTitleBar) {
     let tabRowWidget = $('div.tab-row-widget.component')
     tabRowWidget.after(`<div class="title-bar-buttons component" style="contain: none;"></div>`)
}
titleBarButtons = $('div.title-bar-buttons.component')
// Positions the widget next to Title bar buttons
titleBarButtons.prepend(this.$widget)
```

`isNativeTitleBar` holds a result of a function that fetches the setting from the database.

If the widget detects that Native Title Bar is enabled, it should create a container for the widget, just after the div element with "tab-row-widget component" classes.
Then it searches for the div element with classes "title-bar-buttons component" (element added in the previous step) and inserts the widget's button as a first child. 
If the widget detects that Native Title Bar is disabled it only performs the latter (with the difference being that the element should already exist, created by Trilium).
If it looks like this maybe the CSS is overridden or not loaded correctly.

**Comment by dariuszszyc** [comment]
I have no other widgets installed (it's a fresh install), but I did install a blue theme:
https://github.com/SiriusXT/trilium-theme-blue

Yet I have this issue no matter which theme is active.

I do not see the "title-bar-buttons component" 

![msedge_XKnNAVUTLy](https://github.com/madodig/trilium-widget-theme-switch/assets/41972270/d8999be5-992a-43be-b934-9f49d4306046)

but I do see "tab-row-widget component"

![msedge_twrvncw3z5](https://github.com/madodig/trilium-widget-theme-switch/assets/41972270/727c1d92-e4cb-4c4e-8f38-34c835327c24)

Sorry, I'm not an expert in CSS etc so if you need more details - I can give you AnyDesk details so you could check yourself :)

**Comment by dariuszszyc** [comment]
When I enabled "Native Title Bar" - the dropdown goes nicely to the right :)

![msedge_69dI1XbalS](https://github.com/madodig/trilium-widget-theme-switch/assets/41972270/a0ec4815-39b7-4d5c-bace-10a8076746ec)

**Comment by skyofwing** [comment]
I'm having the same problem. it works fine on the desktop version, but not on the web version.
desktop :
![image](https://github.com/madodig/trilium-widget-theme-switch/assets/23180952/3c194280-d6a4-43cc-a4db-d8febf1f5742)
--
web :
![image](https://github.com/madodig/trilium-widget-theme-switch/assets/23180952/b4c8fbc3-1360-45bf-92d1-55df7bfb62e3)

**Comment by madodig** [comment]
Hi, I published a new release (v.1.2.0). Widget should be properly positioned in both desktop and self-hosted deployments.
